// src/services/api.ts
import axios from 'axios';
import { v4 as uuidv4 } from 'uuid';

const API_URL = 'https://empllo.com/api/v1';

// Define the shape of a job object
interface Job {
  id: string; // Unique ID generated by us
  title: string;
  company: string;
  salary: string;
}

export const fetchJobs = async (): Promise<Job[]> => {
  try {
    const response = await axios.get(API_URL);
    const jobs: Job[] = response.data.map((job: Omit<Job, 'id'>) => ({
      ...job,
      id: uuidv4(), // Assign a unique ID
    }));
    return jobs;
  } catch (error) {
    console.error('Error fetching jobs:', error);
    return [];
  }
};